### ISSUE TITLE
api.get_all_markets() no longer working

### ISSUE THREAD

**Issue by nikosbosse** [vluzko/manifoldpy#124]
Hi there, I was trying to run the following code: 

```
from manifoldpy import api
markets = api.get_all_markets()
print(markets)
```
and got the following error: 

```
...
Fetched 26000 markets.
Fetched 27000 markets.
Fetched 27744 markets.
Traceback (most recent call last):
  File "/Users/nikos/github-synced/Metaculus-data-analyses/comparison-manifold/get-manifold.py", line 6, in <module>
    markets = api.get_all_markets()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikos/github-synced/Metaculus-data-analyses/.venv/lib/python3.11/site-packages/manifoldpy/api.py", line 671, in get_all_markets
    return [Market.from_json(x) for x in _get_all_markets(after=after, limit=limit)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikos/github-synced/Metaculus-data-analyses/.venv/lib/python3.11/site-packages/manifoldpy/api.py", line 671, in <listcomp>
    return [Market.from_json(x) for x in _get_all_markets(after=after, limit=limit)]
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/nikos/github-synced/Metaculus-data-analyses/.venv/lib/python3.11/site-packages/manifoldpy/api.py", line 260, in from_json
    raise ValueError(
ValueError: QUADRATIC_FUNDING isn't a known market outcome type. Submit a bug report if the json came from the API.
```

This looks like a bug to me. Thank you!

**Comment by nikosbosse** [comment]
ok this seems to be fixed on github. Suggested a small change in the readme in #125

**Comment by vluzko** [comment]
I'm going to do a version bump with the new code and then close this

**Comment by vluzko** [comment]
Bumped version.
